[package]
name = "maia-evolution-workspace-host"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
maia-evolution-supervisor = { path = "../evolution-supervisor" }
serde_json = "1"
sha2 = "0.10"
same-file = "1"
fs2 = "0.4.3"
maia-evolution-process-host = { path = "../evolution-process-host" }
